### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by philspencelayh** [dimkroon/itvx-for-kodi#83] opened 2024-04-03 14:58 UTC
running v 1.2.1 on rpi 3b+ OSMC kodi I can watch the short films of the news headlines only. If I try to watch anything else, it allows searches but when I try and open a result the pi crashes I dont have a premium account

**Comment by dimkroon** [comment] 2024-04-03 16:25
Crashing is serious business. Even if an addon misbehaves it should not crash Kodi, or the Operating system. To be able to help it's vital to know what O.S and Kodi version you run and what exactly crashed. Is it Kodi that crashes (blue screen with sad face, restart automatically),  or does the whole OS crash (black screen, manual reboot required) ?

Concerning premium:
The add-on does not treat premium accounts differently from free accounts. Only ITVX returns an error when you want to view a premium video with a free account, which is handled gracefully by the addon and should never lead to a crash anyway.

News clips are mostly plain mp4 files, while other programmes are widevine encoded dash streams. Widevine is a binary from Google and dash is handled by the binary Kodi addon Inputstream Adpative (IA). Both are much more capable of crashing a system than a python add-on like viwX. Ensure you have current versions of Widevine and IA.

As a way to investigate further you could try to play content from addons that use dash without widevine, like e.g. BBC Iplayer-www, and other add-ons that do use widevine , like Netflix.

Also, from experience I can advice you not to disregard the possibility of a faulty GPU.  If you can swap pi's it's worth giving it a try. (after creating a backup image of your SD card, if you don't want to loose anything)

If you need further assistance, here or anywhere else, ensure to add a link to Kodi's debug log, or in your case the crash log (check https://kodi.wiki/view/Log_file how to do that). The chance that it can be fixed in viwX are wery slim, but if you upload a crash log I may be able to help you get closer to the cause of the crash.

**Comment by philspencelayh** [comment] 2024-04-03 17:56
Thanks for getting back so quickly. What was happening was the sad face
then pi rebooted. Reinstalled Wildvine , it still doesn't work but just
stops and reloads kodi. I'll get a different pi and start from  scratch
again.

Phil

**Comment by dimkroon** [comment] 2024-04-03 22:01
Some thoughts that just popped up:
 
Check your power supply. I recall from the day that I upgraded from pi2 to pi3 that my system frequently crashed, which in the end appeared to be all due to a poor power supply. The pi needs sufficient and stable power, which most generic USB adapters do not provide.

If you've changed GPU memory in /boot/config.txt and assigned too much, or too little memory to the GPU you can run into trouble. A clean OSMC install will be OK.

**Comment by philspencelayh** [comment] 2024-04-04 06:53
Thanks, I just got new official PSU this morning and tried it hoping it was
going to fix things but it didn't. I have another 3b+ I'm going to try.
Failing that I'll try my Pi4 but that seems like overkill.

Phil

**Comment by philspencelayh** [comment] 2024-04-05 17:26
Hi, just some feedback I thought may be useful. I tried a fresh OSMC build
on another Pi3b+ using a different type of sd card with the same result. I
then tried on my 4gb Pi4 using  another sd card with the same result. I
noticed that LlbreELEC now supports the version of Kodi that is required to
get the itvX add on to work so I  tried it on a 3b+ and it worked fine.

Phil

**Comment by dimkroon** [comment] 2024-04-11 21:18
Thanks for the feedback @philspencelayh.
Glad you got things working now with LibreElec, but it's a bit of a mystery why OSMC failed you. I use OSMC on a pi4 as my daily production set and have no problems running viwX, or any other addon.

**Closed** 2024-07-02 16:16 UTC
